runtime: python39
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT
env: standard

instance_class: F1  # Choose an appropriate instance class

automatic_scaling:
  min_instances: 0  # Adjust based on your needs
  max_instances: 1  # Adjust based on your needs

env_variables:
  GOOGLE_API_KEY: AIzaSyAkCyb4rrxcMff5oaUzY4W6GmakMzhs12s